application: oruamblog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: blog_controller.app

libraries:
- name: jinja2
  version: 2.6
